# - :site_slug: 'yahf'
#   :building_type: 2
#   :area1: '13'  # 都道府県
#   :area2: '13101,13102' # 市区町村
- :site_slug: 'fdsj'
  :building_type: 2 # 物件種別
  :area1: '13'  # 都道府県
  :area2: '13101,13102'  # 市区町村
# - :site_slug: 'yahf'
#   :building_type: 2
#   :area1: '13'  # 都道府県
#   :area2: '13101' # 市区町村
#   :price_min: '10000000' # 価格(下限)
#   :price_max: '90000000' # 価格(上限)
#   :areasquare_min: '40' # 専有面積（下限）
#   :areasquare_max: '100' # 専有面積（上限）
#   :age_of_building: '5' # 築年数
#   :minutes_to_take: '5' # 最寄り駅徒歩分
#   :floor_plan: '3' # 間取り
# - :site_slug: 'fdsj'
#   :building_type: 2 # 物件種別
#   :area1: '13'  # 都道府県
#   :area2: '13101'  # 市区町村
#   :price_min: '1' # 価格(下限)
#   :price_max: '4' # 価格(上限)
#   :areasquare_min: '20' # 専有面積（下限）
#   :areasquare_max: '70' # 専有面積（上限）
#   :age_of_building: '5' # 築年数
#   :minutes_to_take: '15' # 最寄り駅徒歩分
#   :floor_plan: '1' # 間取り
