# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 780cd132e9a62f63a58f84a0c0c70459a395dd4a25455ac44c87b31352bea57f5a74124c641a9cca9a10c6e44fce23b479d0b8a3f9db1330f1fd4609d8c40d66
  basic_auth_user: <%= ENV["BASICAUTH_USER"] %>
  basic_auth_password: <%= ENV["BASICAUTH_PASSWORD"] %>
  zip_password: <%= ENV["ZIP_PASSWORD"] %>
  smtp_server: <%= ENV["SMTP_SERVER"] %>
  smtp_user: <%= ENV["SMTP_USER"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  mail_from: <%= ENV["MAIL_FROM"] %>
  mail_to: <%= ENV["MAIL_TO"] %>
test:
  secret_key_base: 9f3f2e5711769a93c4e40756461eac82bdb6412669fdb9531c16d0ea8b9b1cf6caf3a5da1e5475bb53db65f992ac5c8c0097a5978e8b20fa04b942fa80b6eb93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  basic_auth_user: <%= ENV["BASICAUTH_USER"] %>
  basic_auth_password: <%= ENV["BASICAUTH_PASSWORD"] %>
  zip_password: <%= ENV["ZIP_PASSWORD"] %>
  smtp_server: <%= ENV["SMTP_SERVER"] %>
  smtp_user: <%= ENV["SMTP_USER"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  mail_from: <%= ENV["MAIL_FROM"] %>
  mail_to: <%= ENV["MAIL_TO"] %>
