html_cache_dir: 'tmp/scraping'
site_slug:
  fdsj: 1
  yahf: 2
search_result_csv_format:
  charset: UTF-8
  endline: LF
  delimiter: ','
  max_filesize: '10MB'
building_type:
  none: 0
  mansion_new: 1
  mansion_used: 2
fdsj:
  price_min:
    'l': '下限なし'
    '1': '1000万円以上'
    '2': '2000万円以上'
    '3': '3000万円以上'
    '4': '4000万円以上'
    '5': '5000万円以上'
    '6': '6000万円以上'
    '7': '7000万円以上'
    '8': '8000万円以上'
    '9': '9000万円以上'
  price_max:
    'h': '上限なし'
    '1': '1000万円未満'
    '2': '2000万円未満'
    '3': '3000万円未満'
    '4': '4000万円未満'
    '5': '5000万円未満'
    '6': '6000万円未満'
    '7': '7000万円未満'
    '8': '8000万円未満'
    '9': '9000万円未満'
  areasquare_min:
    'l': '下限なし'
    '20': '20㎡'
    '40': '40㎡'
    '50': '50㎡'
    '60': '60㎡'
    '70': '70㎡'
    '80': '80㎡'
    '90': '90㎡'
    '100': '100㎡'
    '120': '120㎡'
    '150': '150㎡'
  areasquare_max:
    'h': '上限なし'
    '20': '20㎡'
    '40': '40㎡'
    '50': '50㎡'
    '60': '60㎡'
    '70': '70㎡'
    '80': '80㎡'
    '90': '90㎡'
    '100': '100㎡'
    '120': '120㎡'
    '150': '150㎡'
  age_of_building:
    nil: '指定なし'
    '-1': '指定なし'
    '1': '新築'
    '3': '3年以内'
    '5': '5年以内'
    '10': '10年以内'
    '15': '15年以内'
  minutes_to_take:
    nil: '指定なし'
    '-1': '指定なし'
    '5': '5分以内'
    '10': '10分以内'
    '15': '15分以内'
  floor_plan:
    '1': '1R・1K・1DK'
    '2': '1LDK・2K・2DK'
    '3': '2LDK・3K・3DK'
    '4': '3LDK・4K・4DK'
    '5': '4LDK以上'
yahf:
  price_min:
    nil: '下限なし'
    '10000000': '1,000万円以上'
    '15000000': '1,500万円以上'
    '20000000': '2,000万円以上'
    '25000000': '2,500万円以上'
    '30000000': '3,000万円以上'
    '35000000': '3,500万円以上'
    '40000000': '4,000万円以上'
    '45000000': '4,500万円以上'
    '50000000': '5,000万円以上'
    '55000000': '5,500万円以上'
    '60000000': '6,000万円以上'
    '65000000': '6,500万円以上'
    '70000000': '7,000万円以上'
    '80000000': '8,000万円以上'
    '90000000': '9,000万円以上'
    '100000000': '1億円以上'
  price_max:
    nil: '上限なし'
    '10000000': '1,000万円以下'
    '15000000': '1,500万円以下'
    '20000000': '2,000万円以下'
    '25000000': '2,500万円以下'
    '30000000': '3,000万円以下'
    '35000000': '3,500万円以下'
    '40000000': '4,000万円以下'
    '45000000': '4,500万円以下'
    '50000000': '5,000万円以下'
    '55000000': '5,500万円以下'
    '60000000': '6,000万円以下'
    '65000000': '6,500万円以下'
    '70000000': '7,000万円以下'
    '80000000': '8,000万円以下'
    '90000000': '9,000万円以下'
    '100000000': '1億円以下'
  areasquare_min:
    nil: '下限なし'
    '40': '40㎡以上'
    '50': '50㎡以上'
    '60': '50㎡以上'
    '70': '60㎡以上'
    '80': '70㎡以上'
    '90': '80㎡以上'
    '100': '100㎡以上'
    '120': '120㎡以上'
    '150': '150㎡以上'
  areasquare_max:
    nil: '上限なし'
    '40': '40㎡以下'
    '50': '50㎡以下'
    '60': '50㎡以下'
    '70': '60㎡以下'
    '80': '70㎡以下'
    '90': '80㎡以下'
    '100': '100㎡以下'
    '120': '120㎡以下'
    '150': '150㎡以下'
  age_of_building:
    nil: '指定なし'
    '2': '2年以内'
    '5': '5年以内'
    '10': '10年以内'
    '15': '15年以内'
    '20': '20年以内'
  minutes_to_take:
    nil: '指定なし'
    '3': '3分以内'
    '5': '5分以内'
    '10': '10分以内'
    '15': '15分以内'
    '20': '20分以内'
  floor_plan:
    '1': 'ワンルーム'
    '2': '1K/1DK'
    '3': '1LDK'
    '4': '2K/2DK'
    '5': '2LDK'
    '6': '3K/3DK'
    '7': '3LDK'
    '8': '4K/4DK'
    '9': '4LDK以上'
