site_url:
  fdsj:
    base: 'http://www.fudousan.or.jp/'
    area: 'stub/fdsj_area'
    list: 'stub/fdsj_list'
  yahf:
    base: 'http://realestate.yahoo.co.jp'
    area: 'stub/yahj_area'
    list_page: 'mansion/top/'
  app:
    base: 'http://localhost:3000/'
